### ISSUE TITLE
Help with using rdbg within a docker-compose service

### ISSUE THREAD

**Issue by bmtrann** [ruby/vscode-rdbg#179]
I have a Rails app that is run in Docker Compose with following structure:

```yaml
my-rails-app:
  build: .
  image: my-image
  ports:
    - 3000:3000
    - 1234:1234
  command: ["rdbg", "-n", "--open", "--port", "1234", "-c", "--", "rails", "server", "-b", "0.0.0.0"]
  stdin_open: true
  tty: true
```

I tried following the docs and construct my `launch.json` like the following:

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "rdbg",
            "name": "Debug Rails with rdbg",
            "rdbgPath": "docker-compose exec my-rails-app rdbg",
            "request": "launch",
            "script": "rails s",
            "command": "docker-compose exec my-rails-app rdbg -c",
        },
        {
            "type": "rdbg",
            "name": "Attach with rdbg",
            "request": "attach",
            "rdbgPath": "docker-compose exec my-rails-app rdbg",
            "debugPort": "localhost:1234"
        }
    ]
}
```

I have also put `gem "debug", ">= 1.0.0"` in my `Gemfile`. When pressing F5 to debug, with both `launch` and `attach` mode, VSCode kept saying that it couldnt find the process..

*Couldn't start debug session. The debuggee process exited with code 1* with `launch`
*connect ECONNREFUSED 127.0.0.1:1234* with `attach`

Any help is appreciated, sorry if there's anything unclear since this is my 1st time writing a Github issue!
