### ISSUE TITLE
attach mode doesn't work on v0.2.0

### ISSUE THREAD

**Issue by Kounotori-ssbm** [ruby/vscode-rdbg#250]
Hello, thank you a lot for this awesome extension!

I think vscode debugging for attach mode had worked until yesterday or the day before yesterday.
But after releasing v0.2.0 (maybe), when I start debugging this dialog appears and failed to start debugging.
![image](https://github.com/ruby/vscode-rdbg/assets/19996147/594a6ef2-e4ae-4e78-a068-0b3a55f2a328)
```
bash: cannot set terminal process group (173): Inappropriate ioctl for device
bash: no job control in this shell
```

And, output tab for rdbg says same messages.
![image](https://github.com/ruby/vscode-rdbg/assets/19996147/7601ad33-b673-40bf-a02b-3a5359ecdcae)

## My environment
- Ruby = v3.2.0
- Rails = v7.0.4.2
- rdbg = v.1.7.1
- docker-compose (Docker = v20.10.11, docker-compose = v1.29.2)
- Dev Containers extension v0,292.0
- Windows WSL2 (Ubuntu 20.04)

`docker-compose.yml`
```yml
services:
  api 
    # ...
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rdbg --nonstop --open --command -- rails server --binding=0.0.0.0"
```

`launch.json`
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "rdbg",
      "name": "Attach with rdbg",
      "request": "attach"
    }
  ]
}
```

## v0.1.0 works
After reinstalling v0.1.0, debugging for attach mode has worked again.
![image](https://github.com/ruby/vscode-rdbg/assets/19996147/c8744ead-ae23-4ccb-ac3a-1c80871fab98)

Do I overlook something to use v0.2.0 for attach mode?
